# 服务端口
server:
  port: 8080

spring:
  # 指定环境配置
  profiles:
    active: dev
  # Freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    settings:
      template_update_delay: 0
  # 静态资源路径
  resources:
    static-locations: classpath:/templates/,classpath:/static/


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: my.fast.admin.modules.*.entity
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #字段是否使用下划线命名
    db-column-underline: true
    #动态刷新mapper 调试神器
    refresh-mapper: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false